services:
  - type: web
    name: projeto-vpvn
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromDatabase:
          name: projeto-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: projeto-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: projeto-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: projeto-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: projeto-db
          property: database
      - key: CORS_ORIGIN
        value: https://projeto-vpvn.onrender.com

  - type: pserv
    name: projeto-db
    ipAllowList: [] # allow all
    plan: free
